### ISSUE TITLE
hydrated example

### ISSUE THREAD

**Issue by bestwestern** [DonnieWest/unissist#3]
First of all - freaking awesome library.

> // store state now includes a `hydrated` that tells you whether or not the state has been rehydrated from the store

Could you please elaborate what hydrated does and perhaps add a few lines of example code

**Comment by DonnieWest** [comment]
Thanks! :)

I'm not sure yet how I want to document this, but hopefully the below can clarify some things 👍 

Taking the example from the README:

```js
import createStore from 'unistore'
import persistStore from 'unissist'
import localStorageAdapter from 'unissist/integrations/localStorageAdapter';

const store = createStore({ count: 0 })
const adapter = localStorageAdapter();

persistStore(store, adapter);
```

After this point `store.getState()` should return an object that has a `hydrated` key to inform you when it has retrieved the persisted state from disk.

```js
store.getState(); // should be { hydrated: true, ...restOfState } or { hydrated: false, ...restOfState }
```

A common use case in React would be to delay rendering the rest of your app based on whether or not state has been hydrated from the store while displaying a loading screen:

```js
class Loading extends Component {
  render() {
    if (!this.props.hydrated) {
      return <Loading />;
    }
    return <App />
  }
}

export default connect('hydrated', actions)(Loading);
```

**Comment by bestwestern** [comment]
Thank you for the explanation - I couldn't get the above to work with preact.
I think the problem is me not understanding unistore for Preact - I couldn't connect to 'hydrated' - only the properties given on creation. "count" or "test":

![image](https://user-images.githubusercontent.com/3617433/35510634-2ed32f3c-04f9-11e8-8215-bc72071c8450.png)

Not using connect works (though it is never false ):
`    <span>{store.getState().hydrated ? "t" : "f"}</span>`
