### ISSUE TITLE
How to implement Whitelist/Blacklist?

### ISSUE THREAD

**Issue by hardcoar** [DonnieWest/unissist#4]
im new to this. what's the best way to just select objects i want to persist?

**Comment by DonnieWest** [comment]
On the config object, you can pass in a map function that takes in the unistore state and allows you to return the state you want to persist.

An example might look like:

```
import createStore from 'unistore'
import persistStore from 'unissist'
import localStorageAdapter from 'unissist/integrations/localStorageAdapter';

const store = createStore({ count: 0, dontPersistMe: 1 })
const adapter = localStorageAdapter();

// Default values except migration
let config = {
  version: 1,
  debounceTime: 100,
  // takes in the current state and returns the state to be persisted
  map: state => ({ count: state.count })
}

persistStore(store, adapter, config);
```

This should make it so that `dontPersistMe` doesn't get persisted because it's not included in the returned object from map.
