### ISSUE TITLE
Store refreshing to initial state using map instead of persisting old state.

### ISSUE THREAD

**Issue by coopercc** [DonnieWest/unissist#5]
Currently I have a separate store file that looks like this:
```
import createStore from 'unistore';
import persistStore from 'unissist';
import indexedDBAdapter from 'unissist/integrations/indexdbAdapter';
const initialState = {
    //data
};

const store = createStore(initialState);
const adapter = indexedDBAdapter();

const config = {
    debounceTime: 100,
    map: state => (
        {
            //data
        }   
    )
};
persistStore(store, adapter, config);

store.subscribe((state) => console.log(state));
export default store;
```

If I use `persistStore(store, adapter)` then it will refresh correctly, however using the map, it maps the new store it creates to the adapter then hydrates store. Should this be structured a different way? I am not sure why having the config map out state causes it to default to initial state instead of hydrating. Is there something here that would cause the map to run before it rehydrates?

**Comment by coopercc** [comment]
My theory is that in index.js promise.resolve runs after the timeout does causing the map to run before the adapter can set store state

**Comment by DonnieWest** [comment]
@coopercc I'm having trouble replicating this locally - would you mind supplying either:

1. A test case (perhaps to `unissist.test.js`?)
2. A minimal project that demonstrates the bug

I've tried adding a map function to a personal project and I've fiddled with making a test case, but I'm guessing that I'm missing something

**Comment by coopercc** [comment]
@DonnieWest 
Here is a link to a project to demo what I am talking about plus steps:

[https://github.com/coopercc/preact-test](https://github.com/coopercc/preact-test
)

1. Select either mens/womens
2. Fill out an answer for each question and hit next,
3. on information page, go to shop.
4. Here the state for quizStatus will be finished and view will be shop. The adapter will also have this state
5. Refresh page. It takes me back to the quiz with the initial state instead of keeping the persisted state. If it were persisted, it would have stayed on the shop page.

**Comment by coopercc** [comment]
Also here is a test I tried in unissist.test that failed

```
it('should restore state before mapping', async () => {
    let initialState = { a: 'b', c: 'd' };
    let store = createStore(initialState);
    let cancel = unissist(store, adapter, {
      version: 1,
      debounceTime: 0,
      map: state => ({ a: state.a }),
    }
    );

    expect(adapter.getState()).toBeUndefined();
    store.setState({ a: 'e', c: 'f' });
    await sleep(100);
    expect(await adapter.getState()).toMatchObject({ a: 'e' });
    cancel();

    store = createStore(initialState);
    cancel = unissist(store, adapter, {
      version: 1,
      debounceTime: 0,
      map: state => ({ a: state.a }),
    }
    );

    await sleep(100);
    expect(await store.getState()).toMatchObject({ a: 'e' });
  });
```

Based off of the map, store should look like a:'e' but it keeps it's initial state after it 'restarts'

**Comment by DonnieWest** [comment]
@coopercc aha. I neglected to set the default version of the store when it's persisted. Without a user specifying the version of their state, it'll be dropped when the state is rehydrated.

I supplied a PR #9 that fixes that, and it would require your app's map function to look more like so:

```
    map: ({ quizStatus, ...rest }) => {
        let ret = {
            quizStatus: quizStatus === 'in progress' ? 'intro' : quizStatus,
            ...rest,
        };

        console.log('state mapped', state);
        return ret;
    }
```

Just basically avoid stripping out the version when you map over the state when it's persisted.

Edit: Hrm, your test case tells me this may not be fixed. I might take a look at this again tonight and see if I can figure out what's going on

**Comment by coopercc** [comment]
@DonnieWest  Sweet, thanks for the change!

**Comment by DonnieWest** [comment]
@coopercc this test case seems to pass with lightly modified mapping functions. Mind submitting it as a PR to my branch so I can give you proper credit? :dancer: 

Once you've confirmed it all works for you, I'll merge it in and tag a release

```
  it('should restore state before mapping', async () => {
    let initialState = { a: 'b', c: 'd' };
    let store = createStore(initialState);
    let cancel = unissist(store, adapter, {
      version: 1,
      debounceTime: 0,
      map: ({ a, b, ...rest }) => ({ a, ...rest }),
    });

    expect(adapter.getState()).toBeUndefined();
    store.setState({ a: 'e', c: 'f' });
    await sleep(100);
    expect(await adapter.getState()).toMatchObject({ a: 'e' });
    cancel();

    store = createStore(initialState);
    cancel = unissist(store, adapter, {
      version: 1,
      debounceTime: 0,
      map: ({ a, b, ...rest }) => ({ a, ...rest }),
    });

    await sleep(100);
    console.log('adapter', await adapter.getState());
    console.log('store', await store.getState());
    expect(await store.getState()).toMatchObject({ a: 'e' });
  });
```

**Comment by coopercc** [comment]
Changing my map to below worked.
```
map: ({ quizStatus, newSurvey, ...rest }) => (
        {
            ...rest,
            quizStatus: (quizStatus === 'in progress' ? 'intro' : quizStatus),
        }
    )
```
Thanks!

**Comment by DonnieWest** [comment]
Thanks for helping me with this :man_dancing:
