### ISSUE TITLE
[Suggestion] Allow async migration functions.

### ISSUE THREAD

**Issue by Kanaye** [DonnieWest/unissist#6]
Allowing the migration function to return a promise would allow for different use cases.
For example to only `import()` (or otherwise load code) for migrations from the stores version.
This is usefull when you had lots of breaking changes in the store layout, but don't wan't to ship all migration code in the inital bundle.

To allow for showing user message the store could implement a `migrating` flag which is by default `false`.

To not further delay the store hydration, a check if the returned value is a promise could be made instead of always delaying the execution by a tick.

Edit: if you like the idea I could provide a PR within the next few days.

**Comment by DonnieWest** [comment]
@Kanaye I hadn't thought about this use case, but I like the idea as long as we can keep the library small. I'd love a PR :+1: 

Edit: Thanks in advance :D
